name: eduhope
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - nodejs=18
  - npm
  - sqlite=3.42.0
  - redis=7.0.15
  - ffmpeg=6.0
  - portaudio=19.6.0
  - pip:
    - flask==2.3.3
    - flask-sqlalchemy==3.0.5
    - flask-login==0.6.3
    - flask-socketio==5.3.6
    - flask-migrate==4.0.5
    - flask-cors==4.0.0
    - bcrypt==4.0.1
    - flask-bcrypt==1.0.1
    - PyJWT==2.8.0
    - transformers==4.35.2
    - torch==2.1.0
    - torchvision==0.16.0
    - torchaudio==2.1.0
    - scikit-learn==1.3.2
    - numpy==1.24.3
    - pandas==2.0.3
    - datasets==2.14.6
    - nltk==3.8.1
    - spacy==3.7.2
    - textblob==0.17.1
    - pyttsx3==2.90
    - SpeechRecognition==3.10.0
    - pyaudio==0.2.11
    - opencv-python==4.8.1.78
    - Pillow==10.0.1
    - matplotlib==3.7.2
    - python-socketio==5.9.0
    - eventlet==0.33.3
    - requests==2.31.0
    - better-profanity==0.7.0
    - python-dotenv==1.0.0
    - redis==5.0.1
    - celery==5.3.4
    - schedule==1.2.0
    - emoji==2.8.0
    - gunicorn==21.2.0
    - arcade==2.6.17
    - langdetect==1.0.9
    - librosa==0.10.1
    - soundfile==1.0.0
    - accelerate==0.24.1
    - sentencepiece==0.1.99
    - tokenizers==0.15.0
    - openai==1.3.5
    - huggingface-hub==0.19.4